version = 1

test_patterns = ["spec/**"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "ruby"
enabled = true

  [analyzers.meta]
  plugin = "rubocop"

[[transformers]]
name = "standardrb"
enabled = true